trigger:
  branches:
    include:
      - master

pool:
  name: 'default'  # Your self-hosted agent pool

variables:
  imageName: 'my-react-app'
  acrName: 'acrreactcontainer'
  fullImageName: '$(acrName).azurecr.io/$(imageName):$(Build.BuildId)'

stages:

# -------------------- BUILD STAGE --------------------
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
    - job: BuildJob
      steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'

        - task: Docker@1
          displayName: 'Build Docker Image'
          inputs:
            containerregistrytype: 'Azure Container Registry'
            azureSubscriptionEndpoint: 'React-container-app'
            azureContainerRegistry: 'acrreactcontainer.azurecr.io'
            command: 'Build'
            dockerFile: 'Dockerfile'
            imageName: '$(Build.Repository.Name):$(Build.BuildId)'

# -------------------- PUSH STAGE --------------------
- stage: Push
  displayName: 'Push Docker Image'
  dependsOn: Build
  jobs:
    - job: PushJob
      steps:
        - task: Docker@1
          displayName: 'Push Docker Image'
          inputs:
            containerregistrytype: 'Azure Container Registry'
            azureSubscriptionEndpoint: 'React-container-app'
            azureContainerRegistry: 'acrreactcontainer.azurecr.io'
            command: 'push'
            imageName: '$(Build.Repository.Name):$(Build.BuildId)'

# -------------------- DEPLOY STAGE --------------------
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Push
  jobs:
    - job: DeployJob
      steps:
      - task: AzureWebAppContainer@1
        inputs:
          azureSubscription: 'React-container-app'
          appName: 'React-container-app'
          containers: '$(Build.Repository.Name):$(Build.BuildId)'
        
        #- task: AzureWebApp@1
         # inputs:
         #   azureSubscription: 'React-container-app'
         #   appType: 'webAppLinux'
         #   appName: 'React-container-app'
         #   package: 
            
        #- task: AzureRmWebAppDeployment@5
         # displayName: 'Deploy to App Service'
          #inputs:
           # ConnectionType: 'AzureRM'
            #azureSubscription: 'React-container-app'
           # appType: 'webAppContainer'
            #WebAppName: 'React-container-app'
            #DockerNamespace: 'acrreactcontainer.azurecr.io'
            #DockerRepository: '$(Build.Repository.Name)'
            #DockerImageTag: '$(Build.BuildId)'
