trigger:
  branches:
    include:
      - master

pool:
  name: default


variables:
  imageName: 'my-react-app'
  acrLoginServer: 'acrreactcontainer.azurecr.io'
  fullImageName: '$(acrLoginServer)/$(imageName):$(Build.BuildId)'

stages:

# -------------------- BUILD + PUSH STAGE --------------------
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildPushJob
      displayName: 'Build and Push Job'
      steps:

        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Use Node.js 16.x'
        - task: Docker@2
          displayName: 'Login-ACR'
          inputs:
            containerRegistry: 'Acr-connection-new'
            command: 'login'

       # - task: Docker@2
        #  displayName: 'Login to ACR'
        #  inputs:
         #   command: 'login'
          #  containerRegistry: 'MyAcrConnection'  # Service connection name

        - task: Docker@2
          inputs:
              containerRegistry: 'Acr-connection-new'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile' 

       # - task: Docker@2
        #  displayName: 'Build and Push Docker Image'
         # inputs:
          #  command: 'buildAndPush'
           # repository: '$(imageName)'
            #dockerfile: 'Dockerfile'
           # containerRegistry: 'MyAcrConnection'  # ACR service connection
            #tags: |
             # $(Build.BuildId)

# -------------------- DEPLOY STAGE --------------------
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: BuildAndPush
  jobs:
    - job: DeployJob
      displayName: 'Deploy Job'
      steps:
         - task: AzureWebAppContainer@1
           displayName: 'Deploy'
           inputs:
             azureSubscription: 'React-container-app'
             appName: 'React-container-app'
             containers: '$(fullImageName)'
             
       # - task: AzureWebAppContainer@1
       #  displayName: 'Deploy to Web App Container'
       #   inputs:
       #     azureSubscription: 'React-container-app'
       #     appName: 'React-container-app'
       #     containers: '$(fullImageName)'
