trigger:
  branches:
    include:
      - master

pool:
  name: 'default'  # Your self-hosted agent pool

variables:
  imageName: 'my-react-app'
  acrName: 'myacrhimanshum1'
  fullImageName: '$(acrName).azurecr.io/$(imageName):$(Build.BuildId)'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'Acr-connection'
    repository: '$(acrName).azurecr.io/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)

- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy to App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'React-app-connection'
    appType: 'webAppContainer'
    WebAppName: 'react-appm'
    DockerNamespace: '$(acrName).azurecr.io'
    DockerRepository: '$(imageName)'
    DockerImageTag: '$(Build.BuildId)'
