name: CICD of React Application

on: 
  push: 
    branches: ["Feature-VMSS"]
  pull_request:
    branches: ["Feature-VMSS"]

permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies and build app
        run: |
          npm install
          npm run build

          # Generate server.js for Express
          echo "const express = require('express'); \
          const path = require('path'); \
          const app = express(); \
          const PORT = process.env.PORT || 8080; \
          app.use(express.static(path.join(__dirname, 'build'))); \
          app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'build', 'index.html'))); \
          app.listen(PORT, () => console.log('Server running on port', PORT));" > server.js

          npm install express

      - name: Upload app with server
        uses: actions/upload-artifact@v4
        with:
          name: react_app
          path: |
            build
            server.js
            package.json
            package-lock.json
            node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: react_app
          path: .

      - name: List files
        run: ls -R

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ReactappActions"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
