name: CICD of React Application

on: 
   push: 
     branches: ["none"]
   pull_request:
     branches: ["none"]
permissions: 
  contents: read
jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
   - name: checkout code
     uses: actions/checkout@v4.2.2
   - name: node install
     uses: actions/setup-node@v3.9.1
     with:
       node-version: 18.x
   - name: install dependencies
     run: |
       npm install
       npm run build

   - name: publish artifact
     uses: actions/upload-artifact@v4.6.2
     with:
      name: react_build
      path: build/
      
   - name: List build output
     run: ls -R build/
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
       name: react_build
       path: build/
    - name: List downloaded files 
      run: ls -R build/ 
   
    #- name: build app
     # uses: Azure/appservice-build@v3
    - name: deploy to app service
      uses: azure/webapps-deploy@v3
      with:
          app-name: "pyApp"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build/
  
     


  
