name: CICD of React Application

on: 
   push: 
     branches: ["Feature-VMSS"]
   pull_request:
     branches: ["Feature-VMSS"]
permissions: 
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install deps, build, and add serve
        run: |
          npm install
          npm run build
          npm install serve --save

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: react_app
          path: build/
     
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: react_app
          path: .

      - name: List files
        run: ls -R

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ReactappActions"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
  
     


  
